name: Count Lines of Code

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  count-lines:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Count lines of code
        uses: djdefi/cloc-action@6
        with:
          options: --md --report-file=cloc.md

      - name: Commit cloc report
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add cloc.md
          git commit -m 'Update cloc report'
          git push
