name: Code Stats

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-stats:
    runs-on: ubuntu-latest
    steps:
      # Checkout 代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 Git 配置
      - name: Set up Git
        run: |
          git config --global user.name "Muyun2023"
          git config --global user.email "ji.mu@northeastern.edu"

      # 安装依赖并统计代码行数
      - name: Install dependencies and count lines
        run: |
          # 使用 cloc 工具统计代码行数
          sudo apt-get install -y cloc
          cloc --exclude-dir=tests --json . > code_stats.json

      # 提交和推送统计结果
      - name: Commit and push code stats
        run: |
          # 读取代码行数并将其转为 Markdown 格式
          echo "## Code Stats" > code_stats.md
          echo "### Total Lines of Code" >> code_stats.md
          cat code_stats.json | jq '.SUM.code' >> code_stats.md
          
          # 提交更新
          git add code_stats.md
          git commit -m "🧮 Update code stats"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
