name: Update Code Stats

permissions:
  contents: write  # 👈 添加这一段，允许 bot 写入内容

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0' # 每周运行一次
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Count lines of code
        run: |
          bash count_lines.sh > code_stats.md

      - name: Update README
        run: |
          sed -i '/<!-- CODE_STATS_START -->/,/<!-- CODE_STATS_END -->/c\<!-- CODE_STATS_START -->\n'"$(cat code_stats.md)"'\n<!-- CODE_STATS_END -->' README.md

      - name: Commit and push if changed
        run: |
          git config
