name: Code Stats

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-stats:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies and count lines
      - name: Install dependencies and count lines
        run: |
          sudo apt-get install -y cloc
          cloc --exclude-dir=tests --json . > code_stats.json

      # Create Markdown and commit the file
      - name: Commit and push code stats
        run: |
          # Create Markdown file
          echo "## Code Stats" > code_stats.md
          echo "### Total Lines of Code" >> code_stats.md
          cat code_stats.json | jq '.SUM.code' >> code_stats.md
          
          # Git commit and push
          git config --global user.name "Muyun2023"
          git config --global user.email "ji.mu@northeastern.edu"
          git add code_stats.md
          git commit -m "🧮 Update code stats"
          git push origin main  # Push to a non-protected branch like `code-stats`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

